name: EternalTags
main: xyz.oribuin.eternaltags.EternalTags
version: '1.1.5'
author: Oribuin
api-version: "1.13"
description: A simple tag plugin alternative to other Tag plugins (With Hex Support)
website: https://oribuin.xyz/
libraries:
  - 'net.kyori:adventure-api:4.11.0'
softdepend:
  - PlaceholderAPI
  - Oraxen
  - ItemsAdder